% Auto-generated by cameraCalibrator app on 01-Nov-2016
%-------------------------------------------------------


% Define images to process
imageFileNames = {'C:\Users\Jack\Documents\METR4202\cal2.png',...
    'C:\Users\Jack\Documents\METR4202\cal4.png',...
    'C:\Users\Jack\Documents\METR4202\cal5.png',...
    'C:\Users\Jack\Documents\METR4202\cal7.png',...
    'C:\Users\Jack\Documents\METR4202\cal10.png',...
    'C:\Users\Jack\Documents\METR4202\cal11.png',...
    'C:\Users\Jack\Documents\METR4202\cal12.png',...
    'C:\Users\Jack\Documents\METR4202\cal13.png',...
    'C:\Users\Jack\Documents\METR4202\cal14.png',...
    'C:\Users\Jack\Documents\METR4202\cal15.png',...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Generate world coordinates of the corners of the squares
squareSize = 1.425000e+01;  % in units of 'mm'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 3, 'WorldUnits', 'mm', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', []);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams, 'CameraCentric');

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
originalImage = imread(imageFileNames{1});
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
